#!/bin/bash

for word in $(cat $2); do
    in=$word.in
    out=$word.out
    cmdin=$(${1} < ${in})
    if [ "$cmdin" = "$(cat $out)" ]; then
        echo Test $word passed
    else
        echo Test $word failed
        echo Expected output: 
        cat $out
        echo Actual output: 
        echo "$cmdin"
    fi
done